dien_electronics:
  model_root: '../checkpoints/electronics_5/'
  model_id: 'dien_electronics'
  dataset_id: 'electronics_5'
  model_name: DIEN

  lr: 0.002
  reg_lambda: 1e-4
  emb_dim: 18
  batch_size: 128
  epochs: 100
  seed: 20001

  use_neg_seq: True # 负历史序列
  gru_type: AUGRU  # "GRU", "AIGRU", "AGRU", "AUGRU"


dien_books:
  model_root: '../checkpoints/books_5/'
  model_id: 'dien_books'
  dataset_id: 'books_5'
  model_name: DIEN

  lr: 1e-3
  reg_lambda: 1e-4
  emb_dim: 18
  batch_size: 128
  epochs: 100
  seed: 20001

  use_neg_seq: True # 负历史序列
  gru_type: AUGRU  # "GRU", "AIGRU", "AGRU", "AUGRU"

dien_beauty:
  model_root: '../checkpoints/beauty_5/'
  model_id: 'dien_beauty'
  dataset_id: 'beauty_5'
  model_name: DIEN

  lr: 1e-3
  reg_lambda: 1e-4
  emb_dim: 18
  batch_size: 128
  epochs: 100
  seed: 20004

  use_neg_seq: True # 负历史序列
  gru_type: AUGRU  # "GRU", "AIGRU", "AGRU", "AUGRU"