fibinet_electronics:
  model_root: '../checkpoints/electronics_5/'
  model_id: 'fibinet_electronics'
  dataset_id: 'electronics_5'
  model_name: FiBiNet

  lr: 1e-3
  reg_lambda: 1e-4
  emb_dim: 18
  batch_size: 128
  epochs: 100
  seed: 20004

  use_neg_seq: False # 负历史序列

fibinet_books:
  model_root: '../checkpoints/books_5/'
  model_id: 'fibinet_books'
  dataset_id: 'books_5'
  model_name: FiBiNet

  lr: 1e-3
  reg_lambda: 1e-4
  emb_dim: 18
  batch_size: 128
  epochs: 100
  seed: 20001

  use_neg_seq: False # 负历史序列


fibinet_beauty:
  model_root: '../checkpoints/beauty_5/'
  model_id: 'fibinet_beauty'
  dataset_id: 'beauty_5'
  model_name: FiBiNet

  lr: 0.002
  reg_lambda: 0.001
  emb_dim: 36
  batch_size: 128
  epochs: 100
  seed: 20001

  use_neg_seq: False # 负历史序列